Using Publish Portal API (#235)
* Updating publish portal API

* Error handling for publish curl

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -88,8 +88,42 @@ jobs:
         env:
           MAVEN_OPTS: -Xmx2g
 
-      - name: Publish artifacts for the latest tag
+      - name: Create bundle to publish
         working-directory: target/checkout
-        run: mvn -B -e jar:jar shade:shade source:jar-no-fork javadoc:jar gpg:sign central-publishing:publish -P release,docker
-        env:
-          MAVEN_OPTS: -Xmx14g
+        run: |
+          mkdir -p central-staging/org/finos/legend/shared
+          cp -R ~/.m2/repository/org/finos/legend/shared central-staging/org/finos/legend/shared
+          find central-staging -type f \( -name "*.xml" -o -name "*.repositories" \) -delete
+          mkdir central-publishing
+          cd central-staging && zip -r ../central-publishing/central-bundle.zip org
+
+      - name: Publish bundle
+        working-directory: target/checkout/central-publishing
+        run: |
+          token=$(printf "$CI_DEPLOY_USERNAME:$CI_DEPLOY_PASSWORD" | base64)
+          httpCode=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Authorization: Bearer $token" --form bundle=@central-bundle.zip https://central.sonatype.com/api/v1/publisher/upload?publishingType=AUTOMATIC)
+          
+          if ["$httpCode" -eq 200 ]; then
+            deploymentId=$(cat response.json)
+            echo "Uploaded bundle. Deployment id is: $deploymentId"
+            echo "DEVELOPMENT_ID=${deploymentId}" >> $GITHUB_ENV
+          else
+            echo "Failed to upload bundle. Got status code $httpCode"
+            echo "Got the following response body:"
+            cat response.json
+            exit 1
+          fi
+
+      - name: Verify deployment status
+        run: |
+          token=$(printf "$CI_DEPLOY_USERNAME:$CI_DEPLOY_PASSWORD" | base64)
+          deploymentId=${{ env.DEVELOPMENT_VERSION }}
+          
+          deploymentState=""
+          
+          while [ "$deploymentState" != "PUBLISHED" ]; do
+            sleep 1m
+            response=$(curl -s -X POST -H "Authorization: Bearer $token" https://central.sonatype.com/api/v1/publisher/status?id=$deploymentId)
+            deploymentState=$(jq -r '.deploymentState' $response)
+            echo "Deployment state for id $deploymentId is $deploymentState"
+          done
